#!/bin/bash -e
IMAGE_NAME=mega-drive-midi-interface
docker build -t $IMAGE_NAME .
docker run \
    -e CIRCLE_BUILD_NUM \
    --rm \
    -v $(pwd):/app \
    -w /app \
    -it \
    $IMAGE_NAME \
    make "$@"
