#!/bin/bash -e
IMAGE_NAME=mega-drive-midi-interface
docker build -t $IMAGE_NAME .
docker run \
    --cap-add=SYS_PTRACE \
    --privileged \
    -p 2345:2345 \
    -e BUILD \
    -e CMOCKA_MESSAGE_OUTPUT \
    -e CMOCKA_XML_FILE \
    --rm \
    -v $(pwd):/app \
    -w /app \
    -it \
    $IMAGE_NAME \
    "$@"
