WAV BellRide "samples/BellRide.wav" 2
WAV BellTree "samples/BellTree.wav" 2
WAV BongoRim "samples/BongoRim.wav" 2
WAV Cabasa "samples/Cabasa.wav" 2
WAV Castanet "samples/Castanet.wav" 2
WAV ChinaCrash "samples/ChinaCrash.wav" 2
WAV Clap "samples/Clap.wav" 2
WAV Clave "samples/Clave.wav" 2
WAV ClosedSlap "samples/ClosedSlap.wav" 2
WAV CowBell "samples/CowBell.wav" 2
WAV Crsh1 "samples/Crsh1.wav" 2
WAV Crsh2 "samples/Crsh2.wav" 2
WAV FlrStudio "samples/FlrStudio.wav" 2
WAV GuiroDown "samples/GuiroDown.wav" 2
WAV GuiroUp "samples/GuiroUp.wav" 2
WAV HiStudio "samples/HiStudio.wav" 2
WAV Hi_HatClosed "samples/Hi_HatClosed.wav" 2
WAV Hi_HatFoot "samples/Hi_HatFoot.wav" 2
WAV Hi_HatHalf_Open "samples/Hi_HatHalf_Open.wav" 2
WAV HighAgogo "samples/HighAgogo.wav" 2
WAV HighConga "samples/HighConga.wav" 2
WAV HighQ "samples/HighQ.wav" 2
WAV HighTimbale "samples/HighTimbale.wav" 2
WAV HighWoodblock "samples/HighWoodblock.wav" 2
WAV LongTaikoHit "samples/LongTaikoHit.wav" 2
WAV LongWhistle "samples/LongWhistle.wav" 2
WAV LowAgogo "samples/LowAgogo.wav" 2
WAV LowBongo "samples/LowBongo.wav" 2
WAV LowFlrStudio "samples/LowFlrStudio.wav" 2
WAV LowStudio "samples/LowStudio.wav" 2
WAV LowTimbale "samples/LowTimbale.wav" 2
WAV LowTumba "samples/LowTumba.wav" 2
WAV LowWoodblock "samples/LowWoodblock.wav" 2
WAV Maracas "samples/Maracas.wav" 2
WAV MdHiStudio "samples/MdHiStudio.wav" 2
WAV MdStudio "samples/MdStudio.wav" 2
WAV MetronomeBell "samples/MetronomeBell.wav" 2
WAV MetronomeClick "samples/MetronomeClick.wav" 2
WAV Piccolo1_1 "samples/Piccolo1_1.wav" 2
WAV Piccolo1_2 "samples/Piccolo1_2.wav" 2
WAV QuicaHi "samples/QuicaHi.wav" 2
WAV QuicaLow "samples/QuicaLow.wav" 2
WAV Ride1 "samples/Ride1.wav" 2
WAV Ride2 "samples/Ride2.wav" 2
WAV RimTap "samples/RimTap.wav" 2
WAV ScratchPull "samples/ScratchPull.wav" 2
WAV ScratchPush "samples/ScratchPush.wav" 2
WAV ShortTaikoHit "samples/ShortTaikoHit.wav" 2
WAV ShortWhistle "samples/ShortWhistle.wav" 2
WAV Slap "samples/Slap.wav" 2
WAV SleighBells "samples/SleighBells.wav" 2
WAV SmallShaker "samples/SmallShaker.wav" 2
WAV Snr1_1 "samples/Snr1_1.wav" 2
WAV Snr1_2 "samples/Snr1_2.wav" 2
WAV Snr2_1 "samples/Snr2_1.wav" 2
WAV Snr2_2 "samples/Snr2_2.wav" 2
WAV Splash "samples/Splash.wav" 2
WAV SquareClick "samples/SquareClick.wav" 2
WAV StdKick "samples/StdKick.wav" 2
WAV StdKick1 "samples/StdKick1.wav" 2
WAV StdKick2 "samples/StdKick2.wav" 2
WAV StdKick3 "samples/StdKick3.wav" 2
WAV StdKick4 "samples/StdKick4.wav" 2
WAV StdKick5 "samples/StdKick5.wav" 2
WAV StdKick6 "samples/StdKick6.wav" 2
WAV StdKick7 "samples/StdKick7.wav" 2
WAV StdSnr1 "samples/StdSnr1.wav" 2
WAV StdSnr2 "samples/StdSnr2.wav" 2
WAV Sticks "samples/Sticks.wav" 2
WAV Tambourine "samples/Tambourine.wav" 2
WAV Triangle "samples/Triangle.wav" 2
WAV VibraSlap "samples/VibraSlap.wav" 2
