SPRITE algor_0 "sprite/algor_0.bmp" 6 1 FAST 0
SPRITE algor_1 "sprite/algor_1.bmp" 6 2 FAST 0
SPRITE algor_2 "sprite/algor_2.bmp" 6 2 FAST 0
SPRITE algor_3 "sprite/algor_3.bmp" 6 2 FAST 0
SPRITE algor_4 "sprite/algor_4.bmp" 6 2 FAST 0
SPRITE algor_5 "sprite/algor_5.bmp" 6 4 FAST 0
SPRITE algor_6 "sprite/algor_6.bmp" 6 4 FAST 0
SPRITE algor_7 "sprite/algor_7.bmp" 6 2 FAST 0
SPRITE activity "sprite/activity.bmp" 1 1 FAST 0
SPRITE spr_load "sprite/load.bmp" 4 1 FAST 0
