#!/bin/bash
set -euo pipefail
SERIAL_PORT=/dev/cu.usbserial-A105J2JO
SCRIPT_DIR="$(dirname $0)"

$SCRIPT_DIR/../docker-make
$SCRIPT_DIR/run-everdrive-x7 bin/out.bin
hairless-midiserial -w -c -d \
	-s $SERIAL_PORT \
	-o "IAC Driver IAC Bus 1" \
	-i "IAC Driver IAC Bus 2"
