#!/bin/bash
set -euo pipefail
SERIAL_PORT=/dev/cu.usbmodem00000000001A1
SCRIPT_DIR="$(dirname $0)"

$SCRIPT_DIR/../docker-make
$SCRIPT_DIR/run-everdrive-pro bin/out.bin
hairless-midiserial -w -c -d \
	-s $SERIAL_PORT \
	-o "IAC Driver IAC Bus 1" \
	-i "IAC Driver IAC Bus 2" \
	-p
