#!/bin/bash
set -euo pipefail
SERIAL_PORT=/dev/cu.usbmodem00000000001A1
SCRIPT_DIR="$(dirname $0)"

$SCRIPT_DIR/../docker-make
$SCRIPT_DIR/upload-everdrive-pro out/rom.bin
$SCRIPT_DIR/run-serialmidi-pro
