#!/usr/bin/env bash
sendmidi dev "IAC Driver IAC Bus 2" hex syx 00 22 77 03 01
sendmidi dev "IAC Driver IAC Bus 2" hex syx 7E 7F 09 01
sendmidi dev "IAC Driver IAC Bus 2" hex syx 00 22 77 05 01
sendmidi dev "IAC Driver IAC Bus 2" hex syx 00 22 77 00 06 06
