#!/bin/bash
REGEN_EXE="$(winepath -w ~/Emulation/Sega\ Mega\ Drive/Regen0972D/regen.exe)"
ROM="$(winepath -w $1)"

WINEDEBUG=-all \
    FREETYPE_PROPERTIES="truetype:interpreter-version=35" \
    wine "$REGEN_EXE" $ROM
