#!/bin/bash
set -eu

cd ~/Projects/mega-drive/serialmidi
source bin/activate

python3 serialmidi.py \
    --serial_name=/dev/cu.usbserial-A105J2JO \
    --midi_in_name="IAC Driver Bus 1" \
    --midi_out_name="IAC Driver Bus 2" \
    --debug
