#!/bin/bash
set -eu

SERIAL_PORT=/dev/cu.usbserial-A105J2JO
RUN_MODE=md

if strings "$@" | head -n 1 | grep "SEGA SSF " &>/dev/null; then
    echo "SSF detected"
    RUN_MODE=ssf
fi

megaedx7-run -runMode $RUN_MODE -serialPort $SERIAL_PORT "$@"
