#!/usr/bin/env bash
set -euo pipefail
. $(dirname $0)/set-var
sendmidi dev "$MDMI_MIDI_PORT" hex syx 00 22 77 03 01
sendmidi dev "$MDMI_MIDI_PORT" hex syx 7E 7F 09 01
sendmidi dev "$MDMI_MIDI_PORT" hex syx 00 22 77 05 01
sendmidi dev "$MDMI_MIDI_PORT" hex syx 00 22 77 00 06 06
